name: New Project
description: Creates a new project
title: "[Bug]: "
labels: ["New Project"]
assignees:
  - aldoclg
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: project_name
    attributes:
      label: Project name
      description: Project name
      placeholder: my_project
    validations:
      required: false
  - type: dropdown
    id: template
    attributes:
      label: Template
      description: What the project template
      options:
        - golang
        - python
        - terraform infra
        - terraform lambda(python)
        - terraform lambda(golang)
        - terraform lambda(javascript)
        - kubernetes
    validations:
      required: true
